# Generated by Django 2.2.4 on 2022-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='label',
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(related_name='labels', to='dropship.Label'),
        ),
    ]
