# Generated by Django 2.2.4 on 2022-08-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0002_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentIssue',
        ),
    ]
