# Generated by Django 2.2.4 on 2022-08-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0003_auto_20220810_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='dropship.Sprint'),
        ),
    ]
