# Generated by Django 2.2.4 on 2022-08-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0005_auto_20220810_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
