# Generated by Django 2.2.4 on 2022-08-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0006_auto_20220810_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in progress', 'in progress'), ('in review', 'in review'), ('code complete ', 'code complete '), ('qa testing', 'qa testing'), ('done', 'done')], max_length=128),
        ),
    ]
